name: Tests WWW

on:
  push:
    paths:
      - "www/**"
      - "supabase/**"
      - ".github/workflows/**"
    branches:
      - "master"
  pull_request:
    paths:
      - "www/**"
      - "supabase/**"
      - ".github/workflows/**"

env:
  GITHUB_TOKEN: ${{ github.token }}
  PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}

jobs:
  test:
    name: Run unit test for WWW
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./www/pnpm-lock.yaml
          cache: "pnpm"
      - name: Install dependencies
        working-directory: ./www
        run: pnpm i
      - name: Build WWW
        working-directory: ./www
        run: pnpm run build
      - name: Run unit tests
        working-directory: ./www
        run: pnpm run test:unit
